### ISSUE TITLE
./run_tests.py "Could not find firefox in your system PATH."

### ISSUE THREAD

**Issue by parmegv** [webfp/tor-browser-selenium#10]
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$ ./run_tests.py /vagrant/tor-browser_en-US
......s...s.sssssEE.......EEEEEEEEEE
======================================================================
ERROR: test_screen_capture (test_tbdriver.ScreenshotTest)
Make sure we can capture the screen.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 153, in test_screen_capture
    canvas_exceptions=[cm.CHECK_TPO_URL]) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_should_fail_with_wrong_sys_socks_port (test_tbdriver.TBDriverFailTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 121, in test_should_fail_with_wrong_sys_socks_port
    tor_cfg=cm.USE_SYSTEM_TOR) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_font_bundling (test_tbdriver.TBDriverOptionalArgs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 223, in test_font_bundling
    with TorBrowserDriver(TBB_PATH, tbb_logfile_path=log_file) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_security_slider_settings_hi (test_tbdriver.TBDriverOptionalArgs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 169, in test_security_slider_settings_hi
    with TorBrowserDriver(TBB_PATH, pref_dict=slider_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_security_slider_settings_low_mid (test_tbdriver.TBDriverOptionalArgs)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 182, in test_security_slider_settings_low_mid
    pref_dict=slider_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_tbb_logfile (test_tbdriver.TBDriverOptionalArgs)
Make sure log file is populated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 199, in test_tbb_logfile
    with TorBrowserDriver(TBB_PATH, tbb_logfile_path=log_file) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_httpseverywhere (test_tbdriver.TBDriverTest)
HTTPSEverywhere should redirect to HTTPS version.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_noscript (test_tbdriver.TBDriverTest)
NoScript should disable WebGL.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_tbdriver_profile_not_modified (test_tbdriver.TBDriverTest)
Visiting a site should not modify the original profile contents.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_tbdriver_simple_visit (test_tbdriver.TBDriverTest)
checktor.torproject.org should detect Tor IP.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 36, in setUp
    self.tb_driver = TorBrowserDriver(TBB_PATH)
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_https_everywhere_disabled (test_tbdriver.TBDriverTestAssumptions)
Make sure the HTTP->HTTPS redirection in the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 260, in test_https_everywhere_disabled
    with TorBrowserDriver(TBB_PATH, pref_dict=disable_HE_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

======================================================================
ERROR: test_noscript_webgl_enabled (test_tbdriver.TBDriverTestAssumptions)
Make sure that when we disable NoScript's WebGL blocking,
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/tor-browser-selenium/tbselenium/test/test_tbdriver.py", line 275, in test_noscript_webgl_enabled
    pref_dict=disable_NS_webgl_pref) as driver:
  File "tbselenium/tbdriver.py", line 56, in __init__
    timeout=60)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 67, in __init__
    firefox_options.binary_location = self.binary if isinstance(self.binary, basestring) else self.binary._get_firefox_start_cmd()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 163, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox

----------------------------------------------------------------------
Ran 36 tests in 35.725s

FAILED (errors=12, skipped=7)
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$ find /vagrant/tor-browser_en-US  -name firefox
/vagrant/tor-browser_en-US/Browser/firefox
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$ date && uname -a
Mon Apr 11 10:09:55 UTC 2016
Linux jessie-amd64 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-2 (2015-04-13) x86_64 GNU/Linux
vagrant@jessie-amd64:/vagrant/tor-browser-crawler/tor-browser-selenium$

**Comment by parmegv** [comment]
selenium/webdriver/firefox/webdriver.py, line 67 asks the firefox binary to find its path.

_get_firefox_start_cmd() in FirefoxBinary, in the specific case of linux, looks for "firefox" in the PATH.

**Comment by parmegv** [comment]
The problem is that in [_get_firefox_start_cmd()](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/firefox_binary.py#L142) it is assumed that `self._start_cmd` is not valid.
In our case, it is and it should return its value.

So a small patch like this in that function makes it work:
`if isinstance(self._start_cmd, basestring):
            return self._start_cmd`

**Comment by gunesacar** [comment]
Thanks @parmegv, for the test and the analysis.

Just for the record, it seems this is due to a Selenium issue and doesn't affect the our tests at the moment.

But we may run into problems when we have Marionette tests as Selenium will try to use the system Firefox binary instead of the modified binary in the TBB folder. It's a good idea to make sure we run the modified Firefox binary from TBB, not the one installed on the system.

**Comment by fowlslegs** [comment]
More specifically the problem is that they run the this seemingly pointless test in [this line](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L67). It's seemingly pointless because `self.binary` is supposed to be a `FirefoxBinary` object and not a `basestring` or `str` object; therefore, it will always fail. If you look at [line 57 in that same file](https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L67) you can see that you can skip that whole mess by initializing an `Options` object and passing it to the call `super(TorBrowserDiver, self).__init__` in the `__init__` method of the `TorBrowserDriver` object we're initializing. If that didn't quite follow, see [this commit](https://github.com/fowlslegs/tor-browser-selenium/commit/8f7c88871735fc86ee0209595e718ea03841ffee) where I've implemented the workaround.

The problem with this, at least for me working in the Ubuntu 14.04 server Docker image built from [this repo](https://github.com/tknerr/ubuntu-vm) is that TBB is not self-contained, so now it's failing because certain libraries libxul.so (the main Firefox library) is wanting to load are not present on this minimal image. But, that's a whole different and much easier to diagnose problem... PR incoming!

**Comment by gunesacar** [comment]
> so now it's failing because certain libraries libxul.so (the main Firefox library) is wanting to load are not present on this minimal image.

That's interesting! These libraries are present in TBB's Browser directory but can't be loaded, right? 

Do you think this implies that in normal (non-minimal) boxes we load libxul.so and other libs from the system, but not the ones shipped with TBB? This can be serious issue.
