### ISSUE TITLE
Example program raises JSONDecodeError

### ISSUE THREAD

**Issue by fcolecumberri** [webfp/tor-browser-selenium#172]
I can't even start the driver, just this program:

```python
from tbselenium.tbdriver import TorBrowserDriver

with TorBrowserDriver('/tmp/p/tor-browser_en-US/') as driver:
    pass
```

returns:

```
Traceback (most recent call last):
  File "/tmp/p/selenium_tor/ts.py", line 4, in <module>
    with TorBrowserDriver('/tmp/p/tor-browser_en-US/') as driver:
  File "/home/franky/.local/lib/python3.10/site-packages/tbselenium/tbdriver.py", line 66, in __init__
    self.options.profile = self.tbb_profile_path
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/firefox/options.py", line 107, in profile
    new_profile = FirefoxProfile(new_profile)
  File "/usr/lib/python3.10/site-packages/selenium/webdriver/firefox/firefox_profile.py", line 63, in __init__
    FirefoxProfile.DEFAULT_PREFERENCES = json.load(default_prefs)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by fcolecumberri** [comment]
Fixed it, for some reason the AUR of selenium leaves `/usr/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver_prefs.json` as an empty file. Once I filled it with Selenium's correct content, this stopped to be the problem.
