### ISSUE TITLE
how to run tor on port 9050?!

### ISSUE THREAD

**Issue by sova32** [webfp/tor-browser-selenium#173]
i do:
```
from tbselenium.tbdriver import TorBrowserDriver
with TorBrowserDriver("/path/to/TorBrowserBundle/") as driver:
    driver.get('https://check.torproject.org')
```
i have:
```
/run/media/vadiki/D_238_GB_WD/Projects/python/anonimous_mail_sender/venv/bin/python /run/media/vadiki/D_238_GB_WD/Projects/python/anonimous_mail_sender/main.py
Traceback (most recent call last):
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/anonimous_mail_sender/main.py", line 2, in <module>
    with TorBrowserDriver("/home/vadiki/Browser/") as driver:
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/anonimous_mail_sender/venv/lib/python3.8/site-packages/tbselenium/tbdriver.py", line 54, in __init__
    self.setup_tbb_paths(tbb_path, tbb_fx_binary_path,
  File "/run/media/vadiki/D_238_GB_WD/Projects/python/anonimous_mail_sender/venv/lib/python3.8/site-packages/tbselenium/tbdriver.py", line 171, in setup_tbb_paths
    raise TBDriverPathError("Invalid Firefox binary %s"
tbselenium.exceptions.TBDriverPathError: Invalid Firefox binary /home/vadiki/Browser/Browser/firefox

Process finished with exit code 1
```
how to run tor on port 9050?!
where is documentation?!

**Comment by gunesacar** [comment]
You should rather use a Tor controller library such as [stem](https://github.com/torproject/stem) to run and configure `tor`.
See, also: https://github.com/webfp/tor-browser-selenium/blob/main/examples/stem_adv.py#L33
