### ISSUE TITLE
Message: Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by sontung2310** [webfp/tor-browser-selenium#186]
Hi,
I am suffering from this error when using your library:
Traceback (most recent call last):
  File "test_local.py", line 13, in <module>
    with TorBrowserDriver("/usr/bin/tor-browser") as driver:
  File "/home/sysadmin/anaconda3/envs/tungbs/lib/python3.8/site-packages/tbselenium/tbdriver.py", line 98, in __init__
    super(TorBrowserDriver, self).__init__(
  File "/home/sysadmin/anaconda3/envs/tungbs/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 196, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/home/sysadmin/anaconda3/envs/tungbs/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/sysadmin/anaconda3/envs/tungbs/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/sysadmin/anaconda3/envs/tungbs/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/home/sysadmin/anaconda3/envs/tungbs/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
![image](https://user-images.githubusercontent.com/62052338/233295401-6ad8a5b8-d89c-4e7d-a00a-f1e34205d8f5.png)

I have installed both Tor, Firefox, geckodriver. Does I missed something, or there are some problems with the package?
I also tried the window version, but it still got the same error.

Thank you!

**Comment by gunesacar** [comment]
As @GraemeMeyerGT's pointed out, this is a very common and not-helpful Selenium error, likely caused by not having a display. You can follow the [headless mode example](https://github.com/webfp/tor-browser-selenium/blob/main/examples/headless.py) to fix this issue.

Please also see the [Troubleshooting](https://github.com/webfp/tor-browser-selenium#troubleshooting) where there's help for this specific problem.
