### ISSUE TITLE
Message: Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by youngsj951104** [webfp/tor-browser-selenium#192]
i tried to use the headless code but it still doesn't work 
(base) [root@dw-dev tortest]# python3 test.py /root/tortest/tor-browser
Traceback (most recent call last):
  File "/root/tortest/test.py", line 28, in <module>
    main()
  File "/root/tortest/test.py", line 24, in main
    headless_visit(args.tbb_path)
  File "/root/tortest/test.py", line 11, in headless_visit
    with TorBrowserDriver(tbb_dir) as driver:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/site-packages/tbselenium/tbdriver.py", line 103, in __init__
    super(TorBrowserDriver, self).__init__(
  File "/usr/python/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    super().__init__(command_executor=executor, options=self.options)
  File "/usr/python/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/usr/python/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/usr/python/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by gunesacar** [comment]
This error means the browser couldn't start for some reason and unfortunately the error messages don't say much about the root cause.

Could you please if the troubleshooting steps help you or not? https://github.com/webfp/tor-browser-selenium#-troubleshooting

**Comment by gunesacar** [comment]
Closing due to inactivity. Feel free to reopen once you went through the troubleshooting steps.
