### ISSUE TITLE
Cannot install tbselenium

### ISSUE THREAD

**Issue by Aphexus** [webfp/tor-browser-selenium#200]
Using cached tbselenium-0.8.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "Z:\Temp\pip-install-3svywnpk\tbselenium_4eafd74b23244e2090155e9c18253572\setup.py", line 4, in <module>
          long_description = f.read()
        File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2727: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

I'm not sure what the issue is but it seems that the setup.py file needs a `encoding="utf8"` on the open of the readme.

**Comment by gunesacar** [comment]
Thanks for reporting @Aphexus. Can you share the exact diff of the your changes, or submit a pull request?

I believe this is due to installing `tbselenium` on Windows, which is unfortunately not supported.

**Comment by Illegal-Services** [comment]
I have the same issue, I'm running Windows while this error occurs.

**Comment by GodzyBB** [comment]
> Thanks for reporting @Aphexus. Can you share the exact diff of the your changes, or submit a pull request?
> 
> I believe this is due to installing `tbselenium` on Windows, which is unfortunately not supported.

I just tried it on windows, same error. Just wondering, do you know what OS supports tbselenium? Really wanna get it to work. Thanks

**Comment by Aphexus** [comment]
in setup.py, change the
with open('README.md') as f:

to

with open('README.md', encoding="utf8") as f:

Readme.md has utf8 and the loader will err because of this.


--------------------------------------------------------
from setuptools import setup

with open('README.md') as f:
    long_description = f.read()

setup(
    author='Gunes Acar',
    name="tbselenium",
    description="Tor Browser automation with Selenium",
    keywords=["tor", "selenium", "tor browser"],
    version="0.8.0",
    long_description=long_description,
    long_description_content_type='text/markdown',
    url='https://github.com/webfp/tor-browser-selenium',
    packages=["tbselenium", "tbselenium.test"],
    install_requires=[
        "selenium>=4"
    ]
)

**Comment by gunesacar** [comment]
Fixed in https://github.com/webfp/tor-browser-selenium/commit/9abefa84d055f1bc416d2c3ef13432c3012dbfa7
Again, since this error only occurs on an unsupported OS no immediate PyPI release will be made.
