### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by motad333** [webfp/tor-browser-selenium#206]
hi
i want to install it at python 3.9 and windows 10 but give me error
Collecting tbselenium
  Using cached tbselenium-0.8.0.tar.gz (23 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\niakan_pc\AppData\Local\Temp\pip-install-tq6kzbcd\tbselenium_96f8328cc6424f359c6f9707361ee8ec\setup.py", line 4, in <module>
          long_description = f.read()
        File "C:\Users\niakan_pc\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2727: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by gunesacar** [comment]
This encoding problem is likely fixed now, but note that  Windows is not supported. You can try to run Linux on Windows, using a container, VM or WSL.
