### ISSUE TITLE
WebDriverException: Message: Invalid Host header localhost

### ISSUE THREAD

**Issue by ultravigilante** [webfp/tor-browser-selenium#214]
Greetings, I've stumbled across this library and intend to use it for a project. I'm using Arch Linux.

My test project looks almost identical to the README:

```py
import tbselenium.common as cm
from tbselenium.tbdriver import TorBrowserDriver
from tbselenium.utils import launch_tbb_tor_with_stem

tbb_dir = "/opt/tor-browser" # added a hard-coded path
tor_process = launch_tbb_tor_with_stem(tbb_dir)

with TorBrowserDriver(tbb_dir, tor_cfg=cm.USE_STEM, tbb_logfile_path="./tbb.log") as driver:
    driver.load_url("https://check.torproject.org/")
    print(driver.page_source)

tor_process.kill()
```

My `requirements.txt`:

```
tbselenium
stem
```

---

I've also made sure to install geckodriver v0.31.0 as directed, I can confirm it in my terminal:

```
geckodriver --version
geckodriver 0.31.0 (b617178ef491 2022-04-06 11:57 +0000)
```

---

The error I get looks like this:

```
$ python main.py /opt/tor-browser; sudo pkill -9 tor # added a pkill because it doesn't close properly yet
/opt/tor-browser
Traceback (most recent call last):
  File "/home/me/repos/work/tor-metrics/main.py", line 9, in <module>
    with TorBrowserDriver(tbb_dir, tor_cfg=cm.USE_STEM, tbb_logfile_path="./tbb.log") as driver:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/tbselenium/tbdriver.py", line 103, in __init__
    super(TorBrowserDriver, self).__init__(
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:59435
```

### Additional Notes

- I've confirmed that Tor opens as expected when launched outside of the library
- If I change `executable_path` to `/opt/tor-browser/firefox` it opens the browser, but nothing further
- Adding `tbb_logfile_path` doesn't output anything in my case
- There are no obvious port conflicts or dependencies I can think of or see
- I've ran `pip -U selenium`, all up-to-date
- I've tried using the latest `geckodriver`
- The port specified in the error is randomized (likely the geckodriver port)
- Tried using the system `tor`, but that doesn't seem to be the issue:

```
systemctl status tor
● tor.service - Anonymizing overlay network for TCP
     Loaded: loaded (/usr/lib/systemd/system/tor.service; enabled; preset: disabled)
     Active: active (running) since Sat 2024-09-14 02:07:50 EDT; 5s ago
 Invocation: 30be72741f9b426d950c132b2b3eec8b
    Process: 2007316 ExecStartPre=/usr/bin/tor -f /etc/tor/torrc --verify-config (code=exited, status=0/SUCCESS)
   Main PID: 2007317 (tor)
      Tasks: 9 (limit: 76897)
     Memory: 35.9M (peak: 37.2M)
        CPU: 541ms
     CGroup: /system.slice/tor.service
             └─2007317 /usr/bin/tor -f /etc/tor/torrc

Sep 14 02:07:50 archlinux Tor[2007317]: Signaled readiness to systemd
Sep 14 02:07:50 archlinux systemd[1]: Started Anonymizing overlay network for TCP.
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 5% (conn): Connecting to a relay
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 10% (conn_done): Connected to a relay
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 14% (handshake): Handshaking with a relay
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 15% (handshake_done): Handshake with a relay done
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Sep 14 02:07:51 archlinux Tor[2007317]: Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Sep 14 02:07:52 archlinux Tor[2007317]: Bootstrapped 100% (done): Done
python main.py /opt/tor-browser; sudo pkill -9 tor
/opt/tor-browser
Traceback (most recent call last):
  File "/home/me/repos/work/tor-metrics/main.py", line 9, in <module>
    with TorBrowserDriver(tbb_dir, tor_cfg=cm.USE_RUNNING_TOR) as driver:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/tbselenium/tbdriver.py", line 103, in __init__
    super(TorBrowserDriver, self).__init__(
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:41889
```

Thanks for your time!

**Comment by ultravigilante** [comment]
For completeness, I tried using vanilla Selenium with Firefox and I'm getting the same issue. I'll close this issue seeing as it isn't caused by `tor-browser-selenium`.

```
python main.py
Traceback (most recent call last):
  File "/home/me/repos/work/tor-metrics/main.py", line 9, in <module>
    driver = webdriver.Firefox()
             ^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/firefox/webdriver.py", line 71, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/me/repos/work/tor-metrics/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Invalid Host header localhost:57145
```

**Comment by ultravigilante** [comment]
This was the solution: https://github.com/SeleniumHQ/selenium/issues/11264#issuecomment-1315549233

Just had to add a line to `/etc/hosts`
