### ISSUE TITLE
Whenever I try to run any of the examples, I get a WebDriverException saying I can't load the profile.

### ISSUE THREAD

**Issue by neatville** [webfp/tor-browser-selenium#84]
```
Traceback (most recent call last):
  File "examples.py", line 3, in <module>
    with TorBrowserDriver("/home/me/Downloads/tor-browser_en-US/") as driver:
  File "/home/me/Downloads/tor-browser_en-US/env/lib/python3.6/site-packages/tbselenium/tbdriver.py", line 59, in __init__
    timeout=cm.TB_INIT_TIMEOUT)
  File "/home/me/Downloads/tor-browser_en-US/env/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 80, in __init__
    self.binary, timeout)
  File "/home/me/Downloads/tor-browser_en-US/env/lib/python3.6/site-packages/selenium/webdriver/firefox/extension_connection.py", line 52, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/home/me/Downloads/tor-browser_en-US/env/lib/python3.6/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/home/me/Downloads/tor-browser_en-US/env/lib/python3.6/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 108, in _wait_until_connectable
    % (self.profile.path))
selenium.common.exceptions.WebDriverException: Message: Can't load the profile. Profile Dir: /tmp/tmpiu_7hssx/webdriver-py-profilecopy If you specified a log_file in the FirefoxBinary constructor, check it for details.

```
I can now see that the error was mentioned here, under troubleshooting: https://github.com/webfp/tor-browser-selenium/blob/master/README.md 
If there was any solution linked there, it's very unclear, at least to me. It looks like the Selenium version I'm using is 3.4.2, Python version I use is 3.6.

**Comment by gunesacar** [comment]
Thanks for the report!
Python 3 should be fine but `tor-browser-selenium` is not compatible with Selenium version 3 and above.

Would you mind downgrading to version required in [setup.py](https://github.com/webfp/tor-browser-selenium/blob/master/setup.py#L12) and try again?

**Comment by gunesacar** [comment]
I'm closing as I think the selenium version should be the culprit here. Feel free to reopen if necessary.
