### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'py.test': 'py.test'

### ISSUE THREAD

**Issue by Juranshine** [webfp/tor-browser-selenium#95]
Traceback (most recent call last):
  File "./run_tests.py", line 25, in <module>
    "term-missing", "--durations=10", test_dir])
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'py.test': 'py.test'

**Comment by gunesacar** [comment]
Thanks for reporting. It looks like you don't have `pytest` installed.

Did you follow the instructions in [test-and-development](https://github.com/webfp/tor-browser-selenium/#test-and-development) section? Specifically you need to run `pip install -r requirements-dev.txt` to install the dependencies.
