### ISSUE TITLE
Connection  Refused Error on initialising TorBrowserDriver object

### ISSUE THREAD

**Issue by txjoe** [webfp/tor-browser-selenium#97]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tbselenium/tbdriver.py", line 57, in __init__
    log_path=tbb_logfile_path)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused
```

Also, the init function of the TorBrowserDriver class seems to be blocking, why is that so ?

**Comment by gunesacar** [comment]
Hi @txjoe , thanks for the report. This is a typical Selenium error; it could be due to incompatible libraries, X being unavailable, Firefox crash and so on.

Could you please run the tests with the stable Tor Browser and let me know if any of them fails? https://github.com/webfp/tor-browser-selenium#test-and-development

The init function calls webdriver's constructor under the hood, which itself is blocking.

**Comment by gunesacar** [comment]
Without the additional info, the most likely explanation is that this is a webdriver issue. Closing...
